### ISSUE TITLE
Cached mapping

### ISSUE THREAD

**Issue by MyRealityCoding** [MyRealityCoding/jpersis#23]
Support cached mapping so mappers can be cached very easily:

### Idea 
By adding a ```@Cached``` annotation to a mapper method its content is connected to the cache:

```java
@Cached
@Select
Collection<MyModel> selectAll();
```
In order to provide caching for default mapping as well, there can be used a CachedDefaultMapper with an additional method called `invalidateCache()`. This mapper can be created via:
```java
CachedDefaultMapper<User> cached = jpersis.cached(myDefaultMapper);
```
**OR**
```java
CachedDefaultMapper<User> cached = jpersis.mapDefault(User.class, true);
```
Take also a look at the cache implementations provided by Java itself.

**Comment by MyRealityCoding** [comment]
There is a particular problem with caching related to model IDs. Any object needs to be identified by an ID which is permanent and does not get changed after its creation. For default mapping there is a simple integer used to identify objects. Unfortunately this requirement of an integer key is not strictly specified. My idea now is:

1. define an interface which needs to be implemented by models
2. use this interface in the cached mapper to access the key-value cache properly

**Comment by MyRealityCoding** [comment]
Okay, this new error bugs me out:

```

de.bitbrain.jpersis.JPersisException: java.lang.NoSuchMethodException: de.bitbrain.jpersis.IdProvider.<init>()

	at de.bitbrain.jpersis.drivers.jdbc.ResultSetReader.readSingle(ResultSetReader.java:92)
	at de.bitbrain.jpersis.drivers.jdbc.ResultSetReader.read(ResultSetReader.java:71)
	at de.bitbrain.jpersis.drivers.jdbc.JDBCDriver.extractObjectFromResult(JDBCDriver.java:98)
	at de.bitbrain.jpersis.drivers.jdbc.JDBCDriver.commit(JDBCDriver.java:88)
	at de.bitbrain.jpersis.core.methods.AbstractMapperMethod.executeInternally(AbstractMapperMethod.java:71)
	at de.bitbrain.jpersis.core.methods.AbstractMapperMethod.execute(AbstractMapperMethod.java:56)
	at de.bitbrain.jpersis.core.Proxy.invoke(Proxy.java:60)
	at net.bytebuddy.renamed.java.lang.$Proxy30.getById(Unknown Source)
	at de.bitbrain.jpersis.JPersisTest.testDefaultMapping(JPersisTest.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:31)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:31)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NoSuchMethodException: de.bitbrain.jpersis.IdProvider.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at de.bitbrain.jpersis.drivers.jdbc.ResultSetReader.readSingle(ResultSetReader.java:80)
	... 56 more
```
Apparently it has something to do with the ```extends IdProvider``` statement in the jpersis class.
